version: '3.9'
services:
  # BACKEND API
  lifedex-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/lifedex-api
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/lifedex-api'
